# Generated by Django 6.0.5 on 2026-05-09 17:42

import apps.tournaments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Кінець')),
                ('tech_requirements', models.JSONField(blank=True, help_text="Список об'єктів [{category, value}]", null=True, verbose_name='Вимоги до технологій')),
                ('must_have', models.JSONField(blank=True, help_text='Список рядків ["вимога 1", "вимога 2"]', null=True, verbose_name="Must have — обов'язкові критерії")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва турніру')),
                ('description', models.TextField(verbose_name='Опис')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Правила')),
                ('image_mode', models.CharField(default='stock', max_length=50)),
                ('stock_image', models.CharField(blank=True, max_length=255, null=True)),
                ('accent_color', models.CharField(default='#378ADD', max_length=20)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='tournaments/custom/')),
                ('tournament_type', models.CharField(choices=[('solo', 'Одиночний'), ('team', 'Командний')], default='solo', max_length=10, verbose_name='Тип турніру')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('max_teams', models.IntegerField(blank=True, null=True)),
                ('min_team_size', models.IntegerField(blank=True, null=True)),
                ('max_team_size', models.IntegerField(blank=True, null=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invite_pin', models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6)),
                ('jury_invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('jury_invite_pin', models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6)),
                ('admin_invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('admin_invite_pin', models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6)),
                ('leaderboard_published', models.BooleanField(default=False)),
                ('registration_exception_until', models.DateTimeField(blank=True, null=True, verbose_name='Реєстрація відкрита до (виняток)')),
            ],
        ),
        migrations.CreateModel(
            name='RoundAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rounds/attachments/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tournaments.round')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tournaments.round')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/attachments/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tournaments.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tournaments.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва завдання')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис завдання')),
                ('tech_requirements', models.JSONField(blank=True, null=True, verbose_name='Вимоги до технологій')),
                ('must_have', models.JSONField(blank=True, null=True, verbose_name='Must have')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tournaments.round')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournaments.task'),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/attachments/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tournaments.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tournaments.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва команди')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контактний Telegram / телефон')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('registered', 'Зареєстрована')], default='draft', max_length=20, verbose_name='Статус команди')),
                ('team_invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен запрошення в команду')),
                ('roster_locked', models.BooleanField(default=False, verbose_name='Склад зафіксований')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капітан')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
                'ordering': ['created_at'],
                'unique_together': {('tournament', 'captain')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tournaments.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict, verbose_name='Бали за критеріями')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Коментар')),
                ('total', models.FloatField(default=0, verbose_name='Загальний бал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оцінювання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL, verbose_name='Журі')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tournaments.submission', verbose_name='Подання')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('submission', 'juror')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Запрошений'), ('accepted', 'У команді')], default='pending', max_length=20, verbose_name='Статус запрошення')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Учасник')),
            ],
            options={
                'verbose_name': 'Учасник команди',
                'verbose_name_plural': 'Учасники команди',
                'ordering': ['added_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TeamUploadPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_permissions', to='tournaments.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_upload_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='JuryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата призначення')),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Журі')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='tournaments.submission', verbose_name='Подання')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='tournaments.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Призначення журі',
                'verbose_name_plural': 'Призначення журі',
                'ordering': ['assigned_at'],
                'unique_together': {('juror', 'submission')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Власник'), ('participant', 'Учасник'), ('jury', 'Журі'), ('admin', 'Адміністратор')], default='participant', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
