# Generated by Django 6.0.2 on 2026-04-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва турніру')),
                ('description', models.TextField(verbose_name='Опис')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Правила')),
                ('image_mode', models.CharField(default='stock', max_length=50)),
                ('stock_image', models.CharField(blank=True, max_length=255, null=True)),
                ('accent_color', models.CharField(default='#378ADD', max_length=20)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('max_teams', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
