# Generated by Django 6.0.5 on 2026-05-10 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['joined_at']},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='added_at',
            new_name='joined_at',
        ),
        migrations.AddField(
            model_name='tournament',
            name='open_registration',
            field=models.BooleanField(default=False, verbose_name='Відкрита реєстрація (учасники можуть приєднатись будь-коли)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийнятий'), ('rejected', 'Відхилений')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
