# Generated by Django 6.0.2 on 2026-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/custom/', verbose_name='Власна обкладинка'),
        ),
    ]
