# Generated by Django 6.0.5 on 2026-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_is_public_registrationfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='open_registration',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено — учасники можуть приєднуватись будь-коли до завершення турніру.', verbose_name='Вільна реєстрація'),
        ),
    ]
