# Generated by Django 6.0.3 on 2026-05-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('participant', 'Учасник'), ('winner', 'Переможець (1 місце)'), ('top3', 'Призери (2–3 місце)'), ('jury', 'Журі')], default='participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='cert_type',
            field=models.CharField(choices=[('participant', 'Учасник'), ('winner', 'Переможець (1 місце)'), ('top3', 'Призери (2–3 місце)'), ('jury', 'Журі')], default='participant', max_length=20),
        ),
    ]
