# Generated by Django 6.0.5 on 2026-05-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryGradingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Унікальний slug у межах турніру. Використовується як ключ у Grade.scores', max_length=80, verbose_name='Ключ (slug)')),
                ('label', models.CharField(max_length=200, verbose_name='Назва критерію')),
                ('max_score', models.PositiveSmallIntegerField(default=10, verbose_name='Максимальний бал')),
                ('group', models.CharField(blank=True, default='', help_text="Необов'язкова назва групи критеріїв (напр. 'Технічна частина')", max_length=100, verbose_name='Група')),
                ('hint', models.CharField(blank=True, default='', help_text='Коротка підказка для журі, що саме оцінювати', max_length=300, verbose_name='Підказка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок відображення')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_criteria', to='tournaments.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Критерій оцінювання',
                'verbose_name_plural': 'Критерії оцінювання',
                'ordering': ['order', 'id'],
                'unique_together': {('tournament', 'key')},
            },
        ),
    ]
