# Generated by Django 6.0.2 on 2026-04-26 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_roundattachment_roundlink_task_taskattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Інвайт-токен'),
        ),
        migrations.CreateModel(
            name='TournamentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Власник'), ('participant', 'Учасник')], default='participant', max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приєднання')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.tournament', verbose_name='Турнір')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Учасник турніру',
                'verbose_name_plural': 'Учасники турніру',
                'ordering': ['joined_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
