# Generated by Django 6.0.2 on 2026-04-26 20:28

import apps.tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_invite_token_tournamentmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='invite_pin',
            field=models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6, verbose_name='PIN-код запрошення'),
        ),
    ]
