# Generated by Django 6.0.2 on 2026-04-29 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_invite_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст відповіді')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Час здачі')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Час оновлення')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Учасник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournaments.task', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Здача роботи',
                'verbose_name_plural': 'Здачі робіт',
                'ordering': ['-submitted_at'],
                'unique_together': {('task', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/attachments/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Назва файлу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tournaments.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Підпис')),
                ('url', models.URLField(max_length=2048, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tournaments.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
