# Generated by Django 6.0.2 on 2026-05-03 18:03

import apps.tournaments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_submission_submissionattachment_submissionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='admin_invite_pin',
            field=models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6, verbose_name='PIN-код (адмін)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='admin_invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Інвайт-токен (адмін)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='jury_invite_pin',
            field=models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6, verbose_name='PIN-код (журі)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='jury_invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Інвайт-токен (журі)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='invite_pin',
            field=models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6, verbose_name='PIN-код (учасник)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Інвайт-токен (учасник)'),
        ),
        migrations.AlterField(
            model_name='tournamentmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Власник'), ('participant', 'Учасник'), ('jury', 'Журі'), ('admin', 'Адміністратор')], default='participant', max_length=20, verbose_name='Роль'),
        ),
    ]
