# Generated by Django 6.0.2 on 2026-05-05 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_admin_invite_pin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict, verbose_name='Бали за критеріями')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Коментар')),
                ('total', models.FloatField(default=0, verbose_name='Загальний бал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оцінювання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL, verbose_name='Журі')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tournaments.submission', verbose_name='Подання')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'ordering': ['-updated_at'],
                'unique_together': {('submission', 'juror')},
            },
        ),
    ]
