# Generated by Django 6.0.2 on 2026-05-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_grade'),
        ('tournaments', '0010_add_leaderboard_published'),
    ]

    operations = [
    ]
