# Generated by Django 6.0.3 on 2026-05-08 20:16

import apps.tournaments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_merge_0009_grade_0010_add_leaderboard_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='tournamentmember',
            options={'ordering': ['joined_at']},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_team_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. учасників у команді'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('solo', 'Одиночний'), ('team', 'Командний')], default='solo', max_length=10, verbose_name='Тип турніру'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='juror',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='grade',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tournaments.submission'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roundattachment',
            name='file',
            field=models.FileField(upload_to='rounds/attachments/'),
        ),
        migrations.AlterField(
            model_name='roundattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='roundlink',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roundlink',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournaments.task'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(upload_to='submissions/attachments/'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionlink',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionlink',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='tasks/attachments/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklink',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklink',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='admin_invite_pin',
            field=models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='admin_invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/custom/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='invite_pin',
            field=models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='jury_invite_pin',
            field=models.CharField(default=apps.tournaments.models.generate_invite_pin, max_length=6),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='jury_invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='leaderboard_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournamentmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Власник'), ('participant', 'Учасник'), ('jury', 'Журі'), ('admin', 'Адміністратор')], default='participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentmember',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва команди')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капітан')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Учасники')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('tournament', 'captain')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tournaments.team', verbose_name='Команда'),
        ),
        migrations.CreateModel(
            name='TeamUploadPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_permissions', to='tournaments.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_upload_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
