# Generated by Django 6.0.2 on 2026-05-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_merge_0009_grade_0010_add_leaderboard_published'),
        ('tournaments', '0012_tournament_end_date_team_size'),
    ]

    operations = [
    ]
