# Generated by Django 6.0.2 on 2026-05-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_merge_20260508_1918'),
        ('tournaments', '0014_tournament_registration_exception_until'),
    ]

    operations = [
    ]
