# Generated by Django 6.0.2 on 2026-05-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_merge_20260508_2051'),
        ('tournaments', '0016_round_task_tech_requirements_must_have'),
    ]

    operations = [
    ]
