# Generated by Django 6.0.2 on 2026-05-09 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_merge_20260509_0818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='must_have',
            field=models.JSONField(blank=True, null=True, verbose_name='Must have'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tech_requirements',
            field=models.JSONField(blank=True, null=True, verbose_name='Вимоги до технологій'),
        ),
        migrations.CreateModel(
            name='JuryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата призначення')),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Журі')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='tournaments.submission', verbose_name='Подання')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='tournaments.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Призначення журі',
                'verbose_name_plural': 'Призначення журі',
                'ordering': ['assigned_at'],
                'unique_together': {('juror', 'submission')},
            },
        ),
    ]
