# Generated by Django 6.0.3 on 2026-04-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_profile_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('team', 'Team'), ('jury', 'Jury')], default='team', max_length=10),
        ),
    ]
