# Generated by Django 6.0.2 on 2026-04-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_profile_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('participant', 'Participant'), ('jury', 'Jury')], default='participant', max_length=20),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
